version: "3"

services:
  smack:
    image: node
    container_name: smack-server
    volumes:
      - .:/opt/smack
    working_dir: /opt/smack
    ports:
      - '3005:3005'
    environment:
      PORT: 3005
      MONGODB_URI: 'mongodb://chat:chat@mongodb:27017/chat-api'
    links:
      - mongodb
    command:
      bash -c "npm i && npm run build && npm start"

  mongodb:
    image: mongo
    container_name: smack-mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: smack
      MONGO_INITDB_ROOT_PASSWORD: smack@smack

  mongo-express:
    image: mongo-express
    container_name: smack-mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: smack
      ME_CONFIG_MONGODB_ADMINPASSWORD: smack@smack
    links:
      - mongodb
